"""Print a summary of a LAS or LAZ file and a sample of its points.

    python -m lazpy cloud.laz [num_points]

Installed as the ``lazpy`` command too. Reading a file this way asks the
library most of what it can be asked about one, which is what makes it worth
shipping rather than keeping beside the source.
"""
import importlib.util
import sys

from .formats import Chunking, PROJECTION_VLR_KEYS
from .reader import Reader


def _crs(reader):
    """What the file says about its projection, in a line, or None.

    Asked only of a file that carries a projection record at all, since
    Reader.crs imports pyproj whatever the answer turns out to be and that
    import costs more than the rest of a summary put together. A summary is
    worth having without pyproj installed, so its absence leaves the line out
    rather than ending the run.
    """
    header = reader.header
    if not any(key in header['variable_length_records']
               or key in header['extended_variable_length_records']
               for key in PROJECTION_VLR_KEYS):
        return None
    if importlib.util.find_spec('pyproj') is None:
        return None

    crs = reader.crs
    if crs is None:
        return None
    code = crs.to_epsg()
    return crs.name if code is None else f"{crs.name} (EPSG:{code})"


def summarize(reader):
    header = reader.header
    print(f"file             {reader.header['file_signature'].decode()} "
          f"{header['version_major']}.{header['version_minor']}")
    software = header['generating_software'].decode(errors='replace')
    print(f"generated by     {software}")
    print(f"point format     {reader.point_format}"
          f" ({header['point_data_record_length']} bytes/record)")
    print(f"compressed       {reader.is_compressed}")
    if reader.is_compressed:
        laz = reader.laz_header
        versions = sorted({item['version'] for item in laz['items']})
        print(f"laz compressor   {laz['compressor']} "
              f"(item version{'s' if len(versions) > 1 else ''} "
              f"{', '.join(map(str, versions))})")
        if reader.chunking is Chunking.FIXED:
            chunking = f"fixed, {reader.chunk_size} points per chunk"
        elif reader.chunking is Chunking.ADAPTIVE:
            chunking = "adaptive (sizes in the chunk table)"
        else:
            chunking = "none (one stream)"
        print(f"chunking         {chunking}")
    evlrs = header['extended_variable_length_records']
    if evlrs:
        # headers only: a payload may be gigabytes, and is read on demand
        users = sorted({user_id.decode(errors='replace')
                        for user_id, _ in evlrs})
        print(f"extended vlrs    {len(evlrs)} ({', '.join(users)})")
    print(f"points           {reader.num_points:,}")
    print(f"extra bytes      {reader.num_extra_bytes}")
    print(f"scales           {reader.scales}")
    print(f"offsets          {reader.offsets}")
    crs = _crs(reader)
    if crs is not None:
        print(f"crs              {crs}")
    print(f"bounds x         {header['min_x']} .. {header['max_x']}")
    print(f"bounds y         {header['min_y']} .. {header['max_y']}")
    print(f"bounds z         {header['min_z']} .. {header['max_z']}")


def main(argv=None):
    """The command line: a file to summarise, and how many points to show."""
    argv = sys.argv[1:] if argv is None else list(argv)
    if not argv:
        print(__doc__)
        return 1
    return summarize_file(argv[0], int(argv[1]) if len(argv) > 1 else 10)


def summarize_file(filename, count):
    with Reader(filename) as reader:
        summarize(reader)

        n = min(count, reader.num_points)
        if not n:
            return 0

        print(f"\nfirst {n} points:")
        print(f"{'i':>6}  {'x':>14} {'y':>14} {'z':>10}  "
              f"{'int':>6} {'ret':>5} {'class':>5}  gps_time")
        for i, point in enumerate(reader.points(0, n)):
            x, y, z = reader.scale(point)
            print(f"{i:>6}  {x:>14.3f} {y:>14.3f} {z:>10.3f}  "
                  f"{point.intensity:>6} "
                  f"{point.return_number}/{point.number_of_returns:<3} "
                  f"{point.classification:>5}  {point.gps_time:.6f}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
