"""Print a summary of a LAS/LAZ file and a sample of its points.

    python script.py cloud.laz [num_points]
"""
import sys

from lazpy import Chunking, Reader


def summarize(reader):
    header = reader.header
    print(f"file             {reader.header['file_signature'].decode()} "
          f"{header['version_major']}.{header['version_minor']}")
    software = header['generating_software'].decode(errors='replace')
    print(f"generated by     {software}")
    print(f"point format     {reader.point_format}"
          f" ({header['point_data_record_length']} bytes/record)")
    print(f"compressed       {reader.is_compressed}")
    if reader.is_compressed:
        laz = reader.laz_header
        versions = sorted({item['version'] for item in laz['items']})
        print(f"laz compressor   {laz['compressor']} "
              f"(item version{'s' if len(versions) > 1 else ''} "
              f"{', '.join(map(str, versions))})")
        if reader.chunking is Chunking.FIXED:
            chunking = f"fixed, {reader.chunk_size} points per chunk"
        elif reader.chunking is Chunking.ADAPTIVE:
            chunking = "adaptive (sizes in the chunk table)"
        else:
            chunking = "none (one stream)"
        print(f"chunking         {chunking}")
    evlrs = header['extended_variable_length_records']
    if evlrs:
        # headers only: a payload may be gigabytes, and is read on demand
        users = sorted({user_id.decode(errors='replace')
                        for user_id, _ in evlrs})
        print(f"extended vlrs    {len(evlrs)} ({', '.join(users)})")
    print(f"points           {reader.num_points:,}")
    print(f"extra bytes      {reader.num_extra_bytes}")
    print(f"scales           {reader.scales}")
    print(f"offsets          {reader.offsets}")
    print(f"bounds x         {header['min_x']} .. {header['max_x']}")
    print(f"bounds y         {header['min_y']} .. {header['max_y']}")
    print(f"bounds z         {header['min_z']} .. {header['max_z']}")


def main(filename, count):
    with Reader(filename) as reader:
        summarize(reader)

        n = min(count, reader.num_points)
        if not n:
            return 0

        print(f"\nfirst {n} points:")
        print(f"{'i':>6}  {'x':>14} {'y':>14} {'z':>10}  "
              f"{'int':>6} {'ret':>5} {'class':>5}  gps_time")
        for i, point in enumerate(reader.points(0, n)):
            x, y, z = reader.scale(point)
            print(f"{i:>6}  {x:>14.3f} {y:>14.3f} {z:>10.3f}  "
                  f"{point.intensity:>6} "
                  f"{point.return_number}/{point.number_of_returns:<3} "
                  f"{point.classification:>5}  {point.gps_time:.6f}")
    return 0


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    sys.exit(main(sys.argv[1], int(sys.argv[2]) if len(sys.argv) > 2 else 10))
